### ISSUE TITLE
EmotionModel.'Predict' of undefined at onPlay

### ISSUE THREAD

**Issue by shreeraj04** [kevinisbest/FrontEnd-EmotionDetection#1]
I am loading the TinyfaceDetectWebcam.html, where the camera is getting stuck and I could see the below issue on console.

Uncaught (in promise) TypeError: Cannot read property 'predict' of undefined
    at onPlay (TinyFaceDetectWebcam.html:165)

It was working before, but i don't know why its not working now. Could be reference issue which I am not sure.

![image](https://user-images.githubusercontent.com/15680777/67364135-9117e680-f58c-11e9-914f-af1f742dfde8.png)

EmotionModel is undefined, sometimes not.

I am not sure whether it is dependent on where we host because in local WampServer I don't have any issue but when I hosted on Remote Server and enabled openSSL for secure connection I see this issue.

**Comment by OllyOli** [comment]
I have the same issue and I don't know how to solve it

**Comment by kevinisbest** [comment]
Hi @OllyOli @shreeraj04,
Sorry for the late reply, please pull the latest version and try again.
I modified the paths of the model and the library.
